export interface QuestionRef {
  id_prova: string;
  id_questao: string;
}

export interface QuestionSetConfig {
  setNumber: number;
  label: string; // e.g. "Semana 01" ou "Conjunto 01"
  title: string;
  topic: string;
  description: string;
  questionCount: number;
  questionIds: QuestionRef[];
}

export interface CourseSets {
  FG: QuestionSetConfig[];
  ADS: QuestionSetConfig[];
  GTI: QuestionSetConfig[];
  CCP: QuestionSetConfig[];
}

export const QUESTION_SETS: CourseSets = {
  ADS: [
    {
      setNumber: 1,
      label: "Semana 01",
      title: "Engenharia de Requisitos & Ciclo de Vida",
      topic: "Engenharia de Software",
      description: "Levantamento de requisitos funcionais e não-funcionais, regras de negócio e histórias de usuário.",
      questionCount: 4,
      questionIds: [
        { id_prova: "2021_ADS", id_questao: "q09" },
        { id_prova: "2021_ADS", id_questao: "q10" },
        { id_prova: "2021_ADS", id_questao: "q11" },
        { id_prova: "2021_ADS", id_questao: "q12" },
      ],
    },
    {
      setNumber: 2,
      label: "Semana 02",
      title: "Modelagem de Software & Diagramas UML",
      topic: "Engenharia de Software",
      description: "Diagramas de classes, casos de uso, sequência e atividades na notação UML.",
      questionCount: 4,
      questionIds: [
        { id_prova: "2021_ADS", id_questao: "q13" },
        { id_prova: "2021_ADS", id_questao: "q14" },
        { id_prova: "2021_ADS", id_questao: "q15" },
        { id_prova: "2021_ADS", id_questao: "q16" },
      ],
    },
    {
      setNumber: 3,
      label: "Semana 03",
      title: "Banco de Dados & Modelagem Relacional",
      topic: "Banco de Dados",
      description: "Modelo entidade-relacionamento (DER), integridade referencial e chaves primárias/estrangeiras.",
      questionCount: 4,
      questionIds: [
        { id_prova: "2021_ADS", id_questao: "q17" },
        { id_prova: "2021_ADS", id_questao: "q18" },
        { id_prova: "2021_ADS", id_questao: "q19" },
        { id_prova: "2021_ADS", id_questao: "q20" },
      ],
    },
    {
      setNumber: 4,
      label: "Semana 04",
      title: "Programação e Orientação a Objetos",
      topic: "Programação e POO",
      description: "Encapsulamento, herança, polimorfismo, classes abstratas e interfaces.",
      questionCount: 4,
      questionIds: [
        { id_prova: "2021_ADS", id_questao: "q21" },
        { id_prova: "2021_ADS", id_questao: "q22" },
        { id_prova: "2021_ADS", id_questao: "q23" },
        { id_prova: "2021_ADS", id_questao: "q24" },
      ],
    },
    {
      setNumber: 5,
      label: "Semana 05",
      title: "Metodologias Ágeis (Scrum & Kanban)",
      topic: "Engenharia de Software",
      description: "Planejamento de sprints, backlog, cerimônias ágeis e entrega contínua.",
      questionCount: 4,
      questionIds: [
        { id_prova: "2021_ADS", id_questao: "q25" },
        { id_prova: "2021_ADS", id_questao: "q26" },
        { id_prova: "2021_ADS", id_questao: "q27" },
        { id_prova: "2021_ADS", id_questao: "q28" },
      ],
    },
    {
      setNumber: 6,
      label: "Semana 06",
      title: "Banco de Dados: Consultas SQL & Normalização",
      topic: "Banco de Dados",
      description: "Junções SQL (Joins), agrupamentos, formas normais (1FN, 2FN, 3FN) e transações ACID.",
      questionCount: 4,
      questionIds: [
        { id_prova: "2021_ADS", id_questao: "q29" },
        { id_prova: "2021_ADS", id_questao: "q30" },
        { id_prova: "2021_ADS", id_questao: "q31" },
        { id_prova: "2021_ADS", id_questao: "q32" },
      ],
    },
    {
      setNumber: 7,
      label: "Semana 07",
      title: "Testes de Software & Garantia de Qualidade",
      topic: "Engenharia de Software",
      description: "Testes unitários, integração, caixa-preta, caixa-branca, TDD e cobertura de código.",
      questionCount: 4,
      questionIds: [
        { id_prova: "2021_ADS", id_questao: "q33" },
        { id_prova: "2021_ADS", id_questao: "q34" },
        { id_prova: "2021_ADS", id_questao: "q35" },
        { id_prova: "2017_ADS", id_questao: "q09" },
      ],
    },
    {
      setNumber: 8,
      label: "Semana 08",
      title: "Padrões de Projeto (Design Patterns - GoF)",
      topic: "Engenharia de Software",
      description: "Padrões criacionais, estruturais e comportamentais (Singleton, Factory, Strategy, Observer).",
      questionCount: 4,
      questionIds: [
        { id_prova: "2017_ADS", id_questao: "q10" },
        { id_prova: "2017_ADS", id_questao: "q11" },
        { id_prova: "2017_ADS", id_questao: "q12" },
        { id_prova: "2017_ADS", id_questao: "q13" },
      ],
    },
    {
      setNumber: 9,
      label: "Semana 09",
      title: "Segurança de Software & OWASP",
      topic: "Redes e Segurança",
      description: "Vulnerabilidades web, SQL Injection, Cross-Site Scripting (XSS), autenticação e sessões.",
      questionCount: 4,
      questionIds: [
        { id_prova: "2017_ADS", id_questao: "q14" },
        { id_prova: "2017_ADS", id_questao: "q15" },
        { id_prova: "2017_ADS", id_questao: "q16" },
        { id_prova: "2017_ADS", id_questao: "q17" },
      ],
    },
    {
      setNumber: 10,
      label: "Semana 10",
      title: "Arquitetura de Software & Microsserviços",
      topic: "Engenharia de Software",
      description: "APIs RESTful, microsserviços, mensageria, desacoplamento e escalabilidade.",
      questionCount: 4,
      questionIds: [
        { id_prova: "2017_ADS", id_questao: "q18" },
        { id_prova: "2017_ADS", id_questao: "q19" },
        { id_prova: "2017_ADS", id_questao: "q20" },
        { id_prova: "2017_ADS", id_questao: "q21" },
      ],
    },
    {
      setNumber: 11,
      label: "Semana 11",
      title: "DevOps, CI/CD e Infraestrutura de Aplicações",
      topic: "Engenharia de Software",
      description: "Pipelines de deploy contínuo, automação de build, testes automatizados e contêineres.",
      questionCount: 4,
      questionIds: [
        { id_prova: "2017_ADS", id_questao: "q22" },
        { id_prova: "2017_ADS", id_questao: "q23" },
        { id_prova: "2017_ADS", id_questao: "q24" },
        { id_prova: "2017_ADS", id_questao: "q25" },
      ],
    },
    {
      setNumber: 12,
      label: "Semana 12",
      title: "Simulado Geral de Revisão ADS",
      topic: "Revisão Geral",
      description: "Síntese dos tópicos mais cobrados nas provas oficiais do ENADE para ADS.",
      questionCount: 4,
      questionIds: [
        { id_prova: "2017_ADS", id_questao: "q26" },
        { id_prova: "2017_ADS", id_questao: "q27" },
        { id_prova: "2017_ADS", id_questao: "q28" },
        { id_prova: "2017_ADS", id_questao: "q29" },
      ],
    },
  ],

  GTI: [
    {
      setNumber: 1,
      label: "Semana 01",
      title: "Fundamentos de Governança & Alinhamento Estratégico",
      topic: "Governança e Gestão de TI",
      description: "Princípios de governança corporativa de TI, valor de negócio e alinhamento de metas.",
      questionCount: 4,
      questionIds: [
        { id_prova: "2021_GTI", id_questao: "q09" },
        { id_prova: "2021_GTI", id_questao: "q10" },
        { id_prova: "2021_GTI", id_questao: "q11" },
        { id_prova: "2021_GTI", id_questao: "q12" },
      ],
    },
    {
      setNumber: 2,
      label: "Semana 02",
      title: "Gestão de Serviços & ITIL 4",
      topic: "Governança e Gestão de TI",
      description: "Sistema de Valor de Serviço (SVS), as 4 dimensões do gerenciamento e catálogo de serviços.",
      questionCount: 4,
      questionIds: [
        { id_prova: "2021_GTI", id_questao: "q13" },
        { id_prova: "2021_GTI", id_questao: "q14" },
        { id_prova: "2021_GTI", id_questao: "q15" },
        { id_prova: "2021_GTI", id_questao: "q16" },
      ],
    },
    {
      setNumber: 3,
      label: "Semana 03",
      title: "Segurança da Informação & Gestão de Riscos",
      topic: "Governança e Gestão de TI",
      description: "Políticas de segurança, normas ISO/IEC 27001/27002, ameaças e matriz de riscos.",
      questionCount: 4,
      questionIds: [
        { id_prova: "2021_GTI", id_questao: "q17" },
        { id_prova: "2021_GTI", id_questao: "q18" },
        { id_prova: "2021_GTI", id_questao: "q19" },
        { id_prova: "2021_GTI", id_questao: "q20" },
      ],
    },
    {
      setNumber: 4,
      label: "Semana 04",
      title: "Redes & Infraestrutura de TI",
      topic: "Redes e Segurança",
      description: "Arquitetura TCP/IP, protocolos de rede, conectividade e disponibilidade de infraestrutura.",
      questionCount: 4,
      questionIds: [
        { id_prova: "2021_GTI", id_questao: "q21" },
        { id_prova: "2021_GTI", id_questao: "q22" },
        { id_prova: "2021_GTI", id_questao: "q23" },
        { id_prova: "2021_GTI", id_questao: "q24" },
      ],
    },
    {
      setNumber: 5,
      label: "Semana 05",
      title: "Framework COBIT & Objetivos de Controle",
      topic: "Governança e Gestão de TI",
      description: "Estrutura do COBIT, domínios de governança e gestão, maturidade de processos e RACI.",
      questionCount: 4,
      questionIds: [
        { id_prova: "2021_GTI", id_questao: "q25" },
        { id_prova: "2021_GTI", id_questao: "q26" },
        { id_prova: "2021_GTI", id_questao: "q27" },
        { id_prova: "2021_GTI", id_questao: "q28" },
      ],
    },
    {
      setNumber: 6,
      label: "Semana 06",
      title: "LGPD & Conformidade Legal em TI",
      topic: "Governança e Gestão de TI",
      description: "Lei Geral de Proteção de Dados, direitos dos titulares, consentimento e atuação do DPO.",
      questionCount: 4,
      questionIds: [
        { id_prova: "2021_GTI", id_questao: "q29" },
        { id_prova: "2021_GTI", id_questao: "q30" },
        { id_prova: "2021_GTI", id_questao: "q31" },
        { id_prova: "2021_GTI", id_questao: "q32" },
      ],
    },
    {
      setNumber: 7,
      label: "Semana 07",
      title: "Acordos de Nível de Serviço (SLA & OLA)",
      topic: "Governança e Gestão de TI",
      description: "Definição de SLAs, métricas de desempenho, tempo de atendimento e satisfação do cliente.",
      questionCount: 4,
      questionIds: [
        { id_prova: "2021_GTI", id_questao: "q33" },
        { id_prova: "2021_GTI", id_questao: "q34" },
        { id_prova: "2021_GTI", id_questao: "q35" },
        { id_prova: "2017_GTI", id_questao: "q09" },
      ],
    },
    {
      setNumber: 8,
      label: "Semana 08",
      title: "Gestão de Incidentes, Problemas e Mudanças",
      topic: "Governança e Gestão de TI",
      description: "Tratamento de incidentes críticos, análise de causa-raiz (problemas) e comitê de mudanças (CAB).",
      questionCount: 4,
      questionIds: [
        { id_prova: "2017_GTI", id_questao: "q10" },
        { id_prova: "2017_GTI", id_questao: "q11" },
        { id_prova: "2017_GTI", id_questao: "q12" },
        { id_prova: "2017_GTI", id_questao: "q13" },
      ],
    },
    {
      setNumber: 9,
      label: "Semana 09",
      title: "Continuidade de Negócios & Disaster Recovery",
      topic: "Governança e Gestão de TI",
      description: "Plano de Continuidade de Negócios (PCN), RPO (Recovery Point Objective) e RTO (Recovery Time Objective).",
      questionCount: 4,
      questionIds: [
        { id_prova: "2017_GTI", id_questao: "q14" },
        { id_prova: "2017_GTI", id_questao: "q15" },
        { id_prova: "2017_GTI", id_questao: "q16" },
        { id_prova: "2017_GTI", id_questao: "q17" },
      ],
    },
    {
      setNumber: 10,
      label: "Semana 10",
      title: "Gestão Financeira & Orçamento de TI",
      topic: "Governança e Gestão de TI",
      description: "CAPEX, OPEX, Custo Total de Propriedade (TCO), retorno sobre investimento (ROI) e contratos.",
      questionCount: 4,
      questionIds: [
        { id_prova: "2017_GTI", id_questao: "q18" },
        { id_prova: "2017_GTI", id_questao: "q19" },
        { id_prova: "2017_GTI", id_questao: "q20" },
        { id_prova: "2017_GTI", id_questao: "q21" },
      ],
    },
    {
      setNumber: 11,
      label: "Semana 11",
      title: "Gestão de Projetos de TI (PMBOK & Ágil)",
      topic: "Governança e Gestão de TI",
      description: "Gerenciamento de escopo, tempo, riscos, qualidade e custos em projetos de tecnologia.",
      questionCount: 4,
      questionIds: [
        { id_prova: "2017_GTI", id_questao: "q22" },
        { id_prova: "2017_GTI", id_questao: "q23" },
        { id_prova: "2017_GTI", id_questao: "q24" },
        { id_prova: "2017_GTI", id_questao: "q25" },
      ],
    },
    {
      setNumber: 12,
      label: "Semana 12",
      title: "Simulado Geral de Revisão GTI",
      topic: "Revisão Geral",
      description: "Síntese dos tópicos de maior recorrência nas provas oficiais do ENADE para GTI.",
      questionCount: 4,
      questionIds: [
        { id_prova: "2017_GTI", id_questao: "q26" },
        { id_prova: "2017_GTI", id_questao: "q27" },
        { id_prova: "2017_GTI", id_questao: "q28" },
        { id_prova: "2017_GTI", id_questao: "q29" },
      ],
    },
  ],

  FG: [
    {
      setNumber: 1,
      label: "Semana 01",
      title: "Ética Profissional & Cidadania",
      topic: "Formação Geral e Sociedade",
      description: "Dilemas éticos, responsabilidade social, integridade e cidadania ativa.",
      questionCount: 4,
      questionIds: [
        { id_prova: "2024_CCP", id_questao: "q01" },
        { id_prova: "2024_CCP", id_questao: "q02" },
        { id_prova: "2024_CCP", id_questao: "q03" },
        { id_prova: "2024_CCP", id_questao: "q04" },
      ],
    },
    {
      setNumber: 2,
      label: "Semana 02",
      title: "Sustentabilidade & Meio Ambiente",
      topic: "Formação Geral e Sociedade",
      description: "Transição energética, impacto ambiental, consumo consciente e ODS (ONU).",
      questionCount: 4,
      questionIds: [
        { id_prova: "2024_CCP", id_questao: "q05" },
        { id_prova: "2024_CCP", id_questao: "q06" },
        { id_prova: "2024_CCP", id_questao: "q07" },
        { id_prova: "2024_CCP", id_questao: "q08" },
      ],
    },
    {
      setNumber: 3,
      label: "Semana 03",
      title: "Direitos Humanos, Inclusão & Diversidade",
      topic: "Formação Geral e Sociedade",
      description: "Equidade racial, de gênero, acessibilidade e respeito aos direitos fundamentais.",
      questionCount: 4,
      questionIds: [
        { id_prova: "2024_CCP", id_questao: "q09" },
        { id_prova: "2024_CCP", id_questao: "q10" },
        { id_prova: "2024_CCP", id_questao: "q11" },
        { id_prova: "2024_CCP", id_questao: "q12" },
      ],
    },
    {
      setNumber: 4,
      label: "Semana 04",
      title: "Ciência, Tecnologia & Sociedade Digital",
      topic: "Formação Geral e Sociedade",
      description: "Impacto das tecnologias na vida cotidiana, privacidade de dados e inteligência artificial.",
      questionCount: 4,
      questionIds: [
        { id_prova: "2024_CCP", id_questao: "q13" },
        { id_prova: "2024_CCP", id_questao: "q14" },
        { id_prova: "2024_CCP", id_questao: "q15" },
        { id_prova: "2024_CCP", id_questao: "q16" },
      ],
    },
    {
      setNumber: 5,
      label: "Semana 05",
      title: "Democracia, Transparência & Políticas Públicas",
      topic: "Formação Geral e Sociedade",
      description: "Participação popular, acesso à informação, transparência e controle social.",
      questionCount: 4,
      questionIds: [
        { id_prova: "2024_CCP", id_questao: "q17" },
        { id_prova: "2024_CCP", id_questao: "q18" },
        { id_prova: "2024_CCP", id_questao: "q19" },
        { id_prova: "2024_CCP", id_questao: "q20" },
      ],
    },
    {
      setNumber: 6,
      label: "Semana 06",
      title: "Cultura, Arte & Patrimônio Histórico",
      topic: "Formação Geral e Sociedade",
      description: "Manifestações culturais brasileiras, preservação patrimonial e diversidade regional.",
      questionCount: 4,
      questionIds: [
        { id_prova: "2024_CCP", id_questao: "q21" },
        { id_prova: "2024_CCP", id_questao: "q22" },
        { id_prova: "2024_CCP", id_questao: "q23" },
        { id_prova: "2024_CCP", id_questao: "q24" },
      ],
    },
    {
      setNumber: 7,
      label: "Semana 07",
      title: "Relações de Trabalho & Economia Moderna",
      topic: "Formação Geral e Sociedade",
      description: "Transformações no mundo do trabalho, automação, gig economy e direitos do trabalhador.",
      questionCount: 4,
      questionIds: [
        { id_prova: "2024_CCP", id_questao: "q25" },
        { id_prova: "2024_CCP", id_questao: "q26" },
        { id_prova: "2024_CCP", id_questao: "q27" },
        { id_prova: "2024_CCP", id_questao: "q29" },
      ],
    },
    {
      setNumber: 8,
      label: "Semana 08",
      title: "Saúde Pública & Qualidade de Vida",
      topic: "Formação Geral e Sociedade",
      description: "Sistema Único de Saúde (SUS), saneamento básico, vacinação e bem-estar coletivo.",
      questionCount: 4,
      questionIds: [
        { id_prova: "2024_CCP", id_questao: "q30" },
        { id_prova: "2024_CCP", id_questao: "q47" },
        { id_prova: "2024_CCP", id_questao: "q49" },
        { id_prova: "2024_CCP", id_questao: "q64" },
      ],
    },
    {
      setNumber: 9,
      label: "Semana 09",
      title: "Comunicação, Mídia & Combate à Desinformação",
      topic: "Formação Geral e Sociedade",
      description: "Fake news, checagem de fatos, liberdade de expressão e letramento midiático.",
      questionCount: 4,
      questionIds: [
        { id_prova: "2021_GTI", id_questao: "q01" },
        { id_prova: "2021_GTI", id_questao: "q02" },
        { id_prova: "2021_GTI", id_questao: "q03" },
        { id_prova: "2021_GTI", id_questao: "q04" },
      ],
    },
    {
      setNumber: 10,
      label: "Semana 10",
      title: "Inteligência Artificial, Ética & Futuro",
      topic: "Formação Geral e Sociedade",
      description: "Viés algorítmico, ética no uso de IA generativa e impactos no mercado de trabalho.",
      questionCount: 4,
      questionIds: [
        { id_prova: "2021_GTI", id_questao: "q05" },
        { id_prova: "2021_GTI", id_questao: "q06" },
        { id_prova: "2021_GTI", id_questao: "q07" },
        { id_prova: "2021_GTI", id_questao: "q08" },
      ],
    },
    {
      setNumber: 11,
      label: "Semana 11",
      title: "Cidadania Global & Geopolítica",
      topic: "Formação Geral e Sociedade",
      description: "Direito internacional, cooperação humanitária, refugiados e governança global.",
      questionCount: 4,
      questionIds: [
        { id_prova: "2021_CCP", id_questao: "q01" },
        { id_prova: "2021_CCP", id_questao: "q02" },
        { id_prova: "2021_CCP", id_questao: "q03" },
        { id_prova: "2021_CCP", id_questao: "q04" },
      ],
    },
    {
      setNumber: 12,
      label: "Semana 12",
      title: "Simulado Geral de Formação Geral",
      topic: "Revisão Geral",
      description: "Síntese dos temas de atualidades, ética e cidadania mais cobrados no ENADE.",
      questionCount: 4,
      questionIds: [
        { id_prova: "2021_CCP", id_questao: "q05" },
        { id_prova: "2021_CCP", id_questao: "q06" },
        { id_prova: "2021_CCP", id_questao: "q07" },
        { id_prova: "2021_CCP", id_questao: "q08" },
      ],
    },
  ],

  CCP: [
    {
      setNumber: 1,
      label: "Semana 01",
      title: "Algoritmos & Complexidade Assintótica",
      topic: "Algoritmos e Estruturas de Dados",
      description: "Notação Big-O, complexidade de tempo e espaço, recursão e análise de algoritmos.",
      questionCount: 4,
      questionIds: [
        { id_prova: "2024_CCP", id_questao: "q09" },
        { id_prova: "2024_CCP", id_questao: "q10" },
        { id_prova: "2024_CCP", id_questao: "q11" },
        { id_prova: "2024_CCP", id_questao: "q12" },
      ],
    },
    {
      setNumber: 2,
      label: "Semana 02",
      title: "Árvores Binárias & Estruturas Balanceadas",
      topic: "Algoritmos e Estruturas de Dados",
      description: "Árvores binárias de busca, árvores AVL, Rubro-Negras e percursos (in-ordem, pré-ordem).",
      questionCount: 4,
      questionIds: [
        { id_prova: "2024_CCP", id_questao: "q13" },
        { id_prova: "2024_CCP", id_questao: "q14" },
        { id_prova: "2024_CCP", id_questao: "q15" },
        { id_prova: "2024_CCP", id_questao: "q16" },
      ],
    },
    {
      setNumber: 3,
      label: "Semana 03",
      title: "Banco de Dados & Álgebra Relacional",
      topic: "Banco de Dados",
      description: "Operações relacionais (projeção, seleção, junção), SQL avançado e normalização.",
      questionCount: 4,
      questionIds: [
        { id_prova: "2024_CCP", id_questao: "q17" },
        { id_prova: "2024_CCP", id_questao: "q18" },
        { id_prova: "2024_CCP", id_questao: "q19" },
        { id_prova: "2024_CCP", id_questao: "q20" },
      ],
    },
    {
      setNumber: 4,
      label: "Semana 04",
      title: "Sistemas Operacionais & Concorrência",
      topic: "Sistemas Operacionais e Arquitetura",
      description: "Processos, threads, semáforos, monitores, exclusão mútua e prevenção de deadlocks.",
      questionCount: 4,
      questionIds: [
        { id_prova: "2024_CCP", id_questao: "q21" },
        { id_prova: "2024_CCP", id_questao: "q22" },
        { id_prova: "2024_CCP", id_questao: "q23" },
        { id_prova: "2024_CCP", id_questao: "q24" },
      ],
    },
    {
      setNumber: 5,
      label: "Semana 05",
      title: "Grafos & Algoritmos de Caminho Mínimo",
      topic: "Algoritmos e Estruturas de Dados",
      description: "Representação de grafos, busca em largura (BFS), profundidade (DFS) e Dijkstra/Prim.",
      questionCount: 4,
      questionIds: [
        { id_prova: "2024_CCP", id_questao: "q25" },
        { id_prova: "2024_CCP", id_questao: "q26" },
        { id_prova: "2024_CCP", id_questao: "q27" },
        { id_prova: "2024_CCP", id_questao: "q28" },
      ],
    },
    {
      setNumber: 6,
      label: "Semana 06",
      title: "Algoritmos de Ordenação & Busca",
      topic: "Algoritmos e Estruturas de Dados",
      description: "Quicksort, Mergesort, Heapsort, busca binária e tabelas de dispersão (Hash).",
      questionCount: 4,
      questionIds: [
        { id_prova: "2024_CCP", id_questao: "q29" },
        { id_prova: "2024_CCP", id_questao: "q30" },
        { id_prova: "2024_CCP", id_questao: "q31" },
        { id_prova: "2024_CCP", id_questao: "q32" },
      ],
    },
    {
      setNumber: 7,
      label: "Semana 07",
      title: "Arquitetura de Computadores & Hierarquia de Memória",
      topic: "Sistemas Operacionais e Arquitetura",
      description: "Pipeline de instruções, memória cache (L1/L2), memória virtual e registradores.",
      questionCount: 4,
      questionIds: [
        { id_prova: "2024_CCP", id_questao: "q33" },
        { id_prova: "2024_CCP", id_questao: "q34" },
        { id_prova: "2024_CCP", id_questao: "q35" },
        { id_prova: "2024_CCP", id_questao: "q36" },
      ],
    },
    {
      setNumber: 8,
      label: "Semana 08",
      title: "Teoria da Computação & Autômatos Finitos",
      topic: "Teoria da Computação e Compiladores",
      description: "Linguagens regulares, autômatos finitos determinísticos (AFD), AFND e gramáticas.",
      questionCount: 4,
      questionIds: [
        { id_prova: "2024_CCP", id_questao: "q37" },
        { id_prova: "2024_CCP", id_questao: "q38" },
        { id_prova: "2024_CCP", id_questao: "q39" },
        { id_prova: "2024_CCP", id_questao: "q40" },
      ],
    },
    {
      setNumber: 9,
      label: "Semana 09",
      title: "Inteligência Artificial & Mineração de Dados",
      topic: "Inteligência Artificial e Dados",
      description: "Algoritmos de busca heurística (A*), aprendizado supervisionado e redes neurais.",
      questionCount: 4,
      questionIds: [
        { id_prova: "2024_CCP", id_questao: "q41" },
        { id_prova: "2024_CCP", id_questao: "q42" },
        { id_prova: "2024_CCP", id_questao: "q43" },
        { id_prova: "2024_CCP", id_questao: "q44" },
      ],
    },
    {
      setNumber: 10,
      label: "Semana 10",
      title: "Redes de Computadores & Segurança de Protocolos",
      topic: "Redes e Segurança",
      description: "Camadas OSI/TCP-IP, roteamento IP, controle de congestionamento TCP e TLS/SSL.",
      questionCount: 4,
      questionIds: [
        { id_prova: "2024_CCP", id_questao: "q45" },
        { id_prova: "2024_CCP", id_questao: "q46" },
        { id_prova: "2024_CCP", id_questao: "q47" },
        { id_prova: "2024_CCP", id_questao: "q48" },
      ],
    },
    {
      setNumber: 11,
      label: "Semana 11",
      title: "Compiladores & Análise Léxica/Sintática",
      topic: "Teoria da Computação e Compiladores",
      description: "Tabelas de símbolos, analisadores LL/LR, árvores de derivação sintática e código intermediário.",
      questionCount: 4,
      questionIds: [
        { id_prova: "2024_CCP", id_questao: "q49" },
        { id_prova: "2024_CCP", id_questao: "q50" },
        { id_prova: "2024_CCP", id_questao: "q51" },
        { id_prova: "2024_CCP", id_questao: "q52" },
      ],
    },
    {
      setNumber: 12,
      label: "Semana 12",
      title: "Simulado Geral de Revisão Ciência da Computação",
      topic: "Revisão Geral",
      description: "Síntese dos tópicos de maior peso nas provas oficiais do ENADE para Ciência da Computação.",
      questionCount: 4,
      questionIds: [
        { id_prova: "2024_CCP", id_questao: "q53" },
        { id_prova: "2024_CCP", id_questao: "q54" },
        { id_prova: "2024_CCP", id_questao: "q55" },
        { id_prova: "2024_CCP", id_questao: "q56" },
      ],
    },
  ],
};

export function getQuestionSetsForCourse(cursoInput: string): QuestionSetConfig[] {
  const c = cursoInput.toUpperCase();
  if (c === "FG" || c.includes("FORMA")) return QUESTION_SETS.FG;
  if (c === "GTI") return QUESTION_SETS.GTI;
  if (c === "CCP") return QUESTION_SETS.CCP;
  return QUESTION_SETS.ADS;
}

export function getQuestionSetByNumber(cursoInput: string, setNumber: number): QuestionSetConfig | null {
  const sets = getQuestionSetsForCourse(cursoInput);
  const found = sets.find((s) => s.setNumber === setNumber);
  return found || sets[0] || null;
}
